export const TYPES = {
	Application: Symbol.for('Application'),
	AuthController: Symbol.for('AuthController'),
	AuthService: Symbol.for('AuthService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	MongoService: Symbol.for('MongoService'),
	AuthRepository: Symbol.for('AuthRepository'),
	CarsController: Symbol.for('CarsController'),
	CarsService: Symbol.for('CarsService'),
	CarsRepository: Symbol.for('CarsRepository'),
	RentalRepository: Symbol.for('RentalRepository'),
	RentalController: Symbol.for('RentalController'),
	RentalService: Symbol.for('RentalSerivce'),
};
